// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Turso in production/when configured, otherwise a local sqlite file so
    // no .env is required to get started with local dev.
    url: process.env["TURSO_DATABASE_URL"] ?? process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
