-- AlterTable
ALTER TABLE "Game" ADD COLUMN "teamABans" TEXT;
ALTER TABLE "Game" ADD COLUMN "teamABarons" INTEGER;
ALTER TABLE "Game" ADD COLUMN "teamADragons" TEXT;
ALTER TABLE "Game" ADD COLUMN "teamAGold" INTEGER;
ALTER TABLE "Game" ADD COLUMN "teamAVoidGrubs" INTEGER;
ALTER TABLE "Game" ADD COLUMN "teamBBans" TEXT;
ALTER TABLE "Game" ADD COLUMN "teamBBarons" INTEGER;
ALTER TABLE "Game" ADD COLUMN "teamBDragons" TEXT;
ALTER TABLE "Game" ADD COLUMN "teamBGold" INTEGER;
ALTER TABLE "Game" ADD COLUMN "teamBVoidGrubs" INTEGER;
